services:
  db:
    image: postgres:15
    container_name: api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M

volumes:
  postgres-data:
    driver: local